<Project Sdk="Microsoft.NET.Sdk">
 
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>UpsMaintenanceApp</AssemblyName>
    <RootNamespace>UpsMaintenanceApp</RootNamespace>
  </PropertyGroup>
 
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.102.2" />
  </ItemGroup>
 
</Project>